### ISSUE TITLE
OCR improvements to textextractor 2.0

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor2.0#2]
[TextExtractor 2.0](http://textextractor2.herokuapp.com/) is an open source web application build using the Flask framework. It extracts text from an image. in order to celebrate this year's hacktoberfest festival this repo is open for all kind of contributions including **Documentation and typo fix**  please do check the [guidelines](https://github.com/Aman-zishan/textextractor2.0/blob/master/CONTRIBUTING.md) before contributing and feel free to add your name to [CONTRIBUTORS.md](https://github.com/Aman-zishan/textextractor2.0/blob/master/CONTRIBUTORS.md) after opening a successful pull request.

- [x] improve OCR by processing the image to greyscale

- [x] Reduce image size before OCR to process images above 2 MB

- [ ] Add custom error page

- [ ] Add other features

**Comment by Vipul-Bajaj** [comment]
I can work on this.

**Comment by Aman-zishan** [comment]
> I can work on this.

Good to hear that!.

please note these

The App is hosted on heroku 
By tomorrow evening **base** branch of this repo will be updated with the latest version from heroku git. So i request you to open pull requests in base branch.

Happy coding!

**Comment by Vipul-Bajaj** [comment]
Can u pls elaborate on the last 2 requirements?

**Comment by Aman-zishan** [comment]
> Can u pls elaborate on the last 2 requirements?

As of now the application  doesn't cover custom server error. Since by mistake the app was hosted on DEBUG mode.
Add features are meant to be a suggestion from contributors.

**Comment by Vipul-Bajaj** [comment]
Ok Thanks for quick response

**Comment by Vipul-Bajaj** [comment]
Also, for point 2, the app is able to process an image of size greater than 2MB.
Do you want to reduce the size for every incoming image or on a criteria basis, like greater than x*y pixels?

**Comment by Aman-zishan** [comment]
> Also, for point 2, the app is able to process an image of size greater than 2MB.
> Do you want to reduce the size for every incoming image or on a criteria basis, like greater than x*y pixels?

Sometimes it seems the app takes a lot of time then crashes after uploading a file of size in MBs so i thought it would be better to crop the  image to the area having text and apply PIL filters so that it would be reduced in size also greyscale makes OCR easy.

note: base branch has been merged to master and right now the repo is ready to receive contributions by following the [guidelines](https://github.com/Aman-zishan/textextractor2.0/blob/master/CONTRIBUTING.md)

**Comment by Vipul-Bajaj** [comment]
Can u reassign this issue to someone else, I will not be able to work on this. I am extremely sorry for this

**Comment by Aman-zishan** [comment]
> Can u reassign this issue to someone else, I will not be able to work on this. I am extremely sorry for this

no problem. I will reassign, probably i'll be working on this. Thanks for the interest !

happy coding!
