### ISSUE TITLE
Fix and improve UI

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor2.0#4]
It seems there is an extra padding which results in extra space after the footer of the website.

- [ ] Make the website more responsive

- [ ] Improve image alignment 

- [ ] Reduce font size in result page

- [ ] Make the preview image responsive #8 

check #8 for related issue

<p align="center">
<img src="https://user-images.githubusercontent.com/55238388/95010651-b3ddc680-0648-11eb-9182-037ee312bf7b.png" width="75%">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/55238388/95010705-22228900-0649-11eb-8011-ec298f7050b1.png" width="35%">

<img src="https://user-images.githubusercontent.com/55238388/95010786-cb697f00-0649-11eb-8396-4ced57126ee3.png" width="35%">

</p>

**Comment by happycoder0011** [comment]
Can I take this?

**Comment by Aman-zishan** [comment]
> Can I take this?

First two are already under progress now, i will assign the third one to you.

**Comment by Aman-zishan** [comment]
> Can I take this?

update: Those updates didnt go as expected so the first and second still remains.

**Comment by amaanweb** [comment]
Could you please assign it to me.

**Comment by Aman-zishan** [comment]
> Could you please assign it to me.

Which task out of three are you planning to work on? 😄

**Comment by prerna250** [comment]
can i do the first task?

**Comment by millefalcon** [comment]
I think, this issue should be 3 separate issues with all the details for each issue, maybe screenshot if appropriate, under the tag `enhancement`, imho. So it will be more easy to keep track of who is working on what and won't collide :)

**Comment by Aman-zishan** [comment]
> I think, this issue should be 3 separate issues under the tag `enhancement`, imho. So it will be more easy to keep track of who is working on what and won't collide :)

uhmmm that would be better. I'll split this issue and assign the first one to @prerna250

**Comment by millefalcon** [comment]
Sure. Thanks for the consideration :)

**Comment by prerna250** [comment]
thankyou

**Comment by Aman-zishan** [comment]
This issue is now seperated to avoid conflicts. check these #7 #8 😄
