### ISSUE TITLE
Add SEO

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor2.0#5]
configure SEO for better search results.

**Comment by LuizHAP** [comment]
Hello, could you assign me and make the changes mentioned in the link? https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Aman-zishan** [comment]
> Hello, could you assign me and make the changes mentioned in the link? https://hacktoberfest.digitalocean.com/hacktoberfest-update

awesome!. I have already updated the repo with the latest requirements from the official hacktoberfest website. Assigning this to you. 😄
