### ISSUE TITLE
Android version (collaborations are welcome)

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor2.0#6]
https://github.com/Aman-zishan/TextExtractor2.0-android

Calling out all levels of android developers 
Planning to implement flutter or kotlin

**Comment by Prakhar314** [comment]
I'd like to work on this. I can use flutter. It has a tesseract_ocr plugin.

**Comment by Aman-zishan** [comment]
> I'd like to work on this. I can use flutter. It has a tesseract_ocr plugin.

Awesome , i have not started the work yet. So i was thinking of implementing google vision API too. Anyways feel free to open a PR on this [repo](https://github.com/Aman-zishan/TextExtractor2.0-Flutter) for flutter project.

**Comment by Prakhar314** [comment]
Will you start soon? Git doesn't allow forking empty repos I think. 😅

**Comment by Aman-zishan** [comment]
> Will you start soon? Git doesn't allow forking empty repos I think. 😅

Yes empty repos cant  be forked, actually the thing is i was trying to implement this in kotlin/android java. And then i thought i'll move to flutter and i have the ui prototype too. So maybe i can start a demo flutter app and push the code and UI. And then you can fork it.


Also we can take this python code and connect it with flutter.

**Comment by Prakhar314** [comment]
I saw the prototype. Do you intend to show the text as overlaid on the uploaded image or viewed separately or both?

Do you mean using the website as an api server? That would be good I think.

**Comment by Aman-zishan** [comment]
> I saw the prototype. Do you intend to show the text as overlaid on the uploaded image or viewed separately or both?
> 
> Do you mean using the website as an api server? That would be good I think.

UI can be altered just have to keep the color scheme of the website and yes i was thinking of using the website as an api server.

**Comment by Aman-zishan** [comment]
Hey @Prakhar314 API is ready check this #15 for more details on API

This is the API 
http://textextractor2.herokuapp.com/api/v1/
