### ISSUE TITLE
UI improvement -> Add image preview in result page

### ISSUE THREAD

**Issue by Aman-zishan** [Aman-zishan/textextractor2.0#8]
The result page contains only the text extracted and a download button. It would be better if we could show a thumbnail of the image uploaded.

- [x] Add a preview of image to result page

- [ ] make it responsive

<img src="https://user-images.githubusercontent.com/55238388/95010705-22228900-0649-11eb-8011-ec298f7050b1.png" width="35%">

**Comment by happycoder0011** [comment]
I can do this.

**Comment by Aman-zishan** [comment]
> I can do this.

awesome!

**Comment by Lakshitk** [comment]
I would like to be assigned the task to make it responsive

**Comment by Aman-zishan** [comment]
> I would like to be assigned the task to make it responsive

okay cool!

**Comment by Aman-zishan** [comment]
@happycoder0011 Now you can work on #7 now i guess. 😄

**Comment by Aman-zishan** [comment]
This issue is now moved to #4
